**TUGAS PERTEMUAN KE-LIMA**

***5.16 List 2 Dimensi***

List 2 dimensi pada umumnya adalah menempatkan sebuah list. Penggambarannya seperti sebuah matrik

In [1]:
#Latihan list 2 Dimensi (1) dengan elemen yang sama

#inisialisasi variabel 
matrik = [
    [2,4,5,6],
    [8,10,12,14],
    [16,18,20,22],
    [24,26,28,30]
]
#baris ini akan menampilkan elemen dari variabel matrik
print(matrik)

[[2, 4, 5, 6], [8, 10, 12, 14], [16, 18, 20, 22], [24, 26, 28, 30]]


In [2]:
#Latihan list 2 Dimensi (2) dengan elemen yang sama 

#inisialisasi variabel 
matrik = [
    [2,4,5,6],
    [8,10,12,14],
    [16,18,20,22],
    [24,26,28,30]
]
#baris ini akan menampilkan elemen pada baris pertama dari variabel matrik
print(matrik[1])

[8, 10, 12, 14]


In [3]:
#Latihan List 2 Dimensi (3) dengan elemen yang sama 

#inisialisasi variabel 
matrik = [
    [2,4,5,6],
    [8,10,12,14],
    [16,18,20,22],
    [24,26,28,30]
]
#baris ini akan menampilkan elemen pada baris kedua, kolom keempat dari variabel matrik
print(matrik[2][3])

22


In [4]:
#Latihan list 2 Dimensi (4) dengan elemen yang sama dan mengubah elemen pada variabel

#inisialisasi variabel 
matrik = [
    [2,4,5,6],
    [8,10,12,14],
    [16,18,20,22],
    [24,26,28,30]
]
matrik[3][1]=55
#baris ini akan menampilkan elemen matrik pada baris ketiga, kolom kedua dengan 55 dari variabel matrik
print(matrik[3][1])
#baris ini akan menampilkan elemen dari variabel matrik yang sudah dirubah 
print(matrik)

55
[[2, 4, 5, 6], [8, 10, 12, 14], [16, 18, 20, 22], [24, 55, 28, 30]]


In [5]:
#Latihan List 2 Dimensi (5) dengan elemen yang sama 

#inisialisasi variabel 
fakultas = [
    ["kedokteran", "ekonomi", "mipa"],
    ["pertanian", "kelautan", "pertenakan"],
    ["teknik", "fisip", "hukum"]
]
#baris ini akan menampilkan elemen matrik pada baris pertama 
print(fakultas[0][0:])
#baris ini akan menampilkan elemen matrik pada baris pertama, kolom kedua dari belakang 
print(fakultas[1][2:])

['kedokteran', 'ekonomi', 'mipa']
['pertenakan']


In [6]:
#latihan List 2 Dimensi (6) dengan list yang berbeda

#inisialisasi variabel 
program = [
    ["Phyton", "Java", "C++"],
    ["HTML", "PHP", "Java Script"],
    ["Apache"]
]
#baris ini akan menampilkam elemen pada baris kedua
print(program[2][0:])
#baris ini akan menampilkan elemen pada baris kedua
print(program[2])
#kode diatas akan menghasilkan output yang sama, walaupun string yang dimasukkan berbeda 
#mengapa demikian? karena nilai [0:] artinya tidak ada urutan ke-0 dari belakang 

['Apache']
['Apache']


In [7]:
#Latihan list 2 Dimensi (7) dengan menggunakan dua buah list 

#inisialisasi varibel 
nama_minuman1 = ["es jeruk"]
nama_minuman2 = [nama_minuman1, "jus alpukat", "lemon tea"]

#baris ini akan menampilkan elemen dari variabel nama_minuman1 
print(nama_minuman1)
#baris ini akan menampilkan elemen dari variabel nama_minuman2 
print(nama_minuman2)


nama_minuman1[0] = "es teh"
#baris ini akan menampilkan elemen dari variabel nama_minuman1 yang sudah dirubah pada pertama kolom pertama
print(nama_minuman1)

#baris ini akan menampilkan elemen dari variabel nama_minuman2 yang sudah dirubah pada baris pertama kolom pertama
nama_minuman2[0][0] = "es dawet"
print(nama_minuman2)

['es jeruk']
[['es jeruk'], 'jus alpukat', 'lemon tea']
['es teh']
[['es dawet'], 'jus alpukat', 'lemon tea']


In [8]:
#Latihan List 2 Dimensi (8) dengan menggunakan for

#inisialisasi variabel 
fakultas = [
    ["kedokteran", "ekonomi", "mipa"],
    ["pertanian", "kelautan", "pertenakan"],
    ["teknik", "fisip", "hukum"]
]
#baris ini akan memanggil semua baris didalam variabel fakultas
for baris in fakultas :
    print(baris)

['kedokteran', 'ekonomi', 'mipa']
['pertanian', 'kelautan', 'pertenakan']
['teknik', 'fisip', 'hukum']


In [9]:
#Latihan List 2 Dimensi (9) dengan menggunakan for

#inisialisasi variabel 
fakultas = [
    ["kedokteran", "ekonomi", "mipa"],
    ["pertanian", "kelautan", "pertenakan"],
    ["teknik", "fisip", "hukum"]
]
#baris ini akan memanggil kolom ketiga didalam variabel fakultas
for kolom in fakultas :
    print(kolom[2])
#note : kolom/baris akan dihitung mulai dari 0 maka dari itu jika kita ingin menampilkan kolom kedua 
#maka dapat ditulis dengan print(kolom[1])

mipa
pertenakan
hukum


***5.17 Tuples***

Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita
memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan
jika datanya masih ingin dimanipulasi kedepannya, gunakan list.


In [10]:
#Latihan Tuples (1) dengan mengakses dan memotong elemen pada variabel

#inisialisasi variabel 
angka = (0,0,1,1,1,2,2,3,3)

#baris ini akan menampilkan elemen pada urutan 0 dari variabel angka
print(angka[0])
#baris ini akan menampilkan elemen pada urutan pertama hingga ketiga dari variabel angka
print(angka[0:3])

#baris ini akan memanggil elemen pada urutan pertama hingga ketiga dari variabel angka
for isi in angka[0:3]:
    print(isi)
#kode diatas akan menghasilkan output yang sama. Namun, berbeda letaknya jika menggunakan print berbentuk kolom dan jika menggunakan for berbentuk baris  

0
(0, 0, 1)
0
0
1


In [11]:
#latihan Tuples (2) dengan merubah isi pada variabel

#inisialisasi variabel 
huruf = (a,b,b,c,c,c,d,d,d,d)

#baris ini menginisialisasi variabel huruf pada urutan ke-0 dengan  elemen b
huruf[0] = b
#baris ini akan menampilkan elemen ke-0 pada variabel huruf 
print(huruf[0])

#kode ini akan menghasilkan error karena seperti penjelasan arti tuples bahwa tuples tidak dapat dirubah isi nya 

NameError: name 'a' is not defined

In [12]:
#Latihan Tuples (3) dengan menambahkan dan menghapus isi pada variabel

#inisialisasi variabel 
huruf = (a,b,b,c,c,c,d,d,d,d)

#baris ini akan menambahkan elemen b ke dalam variabel huruf
huruf.append(b)
#baris ini akan menampilkan output dari kode diatas
print(huruf)

#baris ini akan menghapus elemen c di variabel huruf
print(huruf.remove(c))
#baris ini akan menampilkan output dari kode diatas 
print(huruf)

#kode ini akan menghasilkan error karena seperti pada penjelasannya bahwa tuples tidak dapat dirubah isinya

NameError: name 'a' is not defined

In [13]:
#Latihan Tuples (4) membuat tuples kosong

#inisialisasi variabel 
tuples_kosong = ()     #jika ingin membuat tuples kosong kita cukup menuliskan dua tanda kurung
#baris ini akan menampilkan elemen pada variabel tuples_kosong
print(tuples_kosong)

()


In [14]:
#Latihan Tuples (5) dengan mendefinisikan tuple yang hanya berisi satu elemen

#inisialisasi variabel 
tuples_tunggal = (10,)  #jika variabel hanya berisi satu elemen kita tetap harus menuliskan tanda koma 
                        #karena jika tidak, maka phyton akan menganggap tanda kurungnya tidak ada 
#baris ini akan menampilkan integer biasa 
print(type((10))) 
#baris ini akan menampilkan yang dianggap sebagao tuples
print(type((10,))) 

<class 'int'>
<class 'tuple'>


In [15]:
#Latihan Tuples (6) dengan menggunakan fitur sequence unpacking

#inisialisasi variabel 
siswa = ("Krisnawan Putra", "Denpasar", 19) 
#ekstrak data atau juga dinamakan sequence unpacking 
nama, asal, usia = siswa 
#setiap variabel di atas akan memiliki nilai dari tiap isi variabel secara berurutan 
print("Nama:", nama)
print("Asal:", asal)
print("Usia:", usia)

Nama: Krisnawan Putra
Asal: Denpasar
Usia: 19


In [16]:
#Latihan Tuples (7) dengan menggabungkan dua buah tuple atau lebih

#inisialisasi variabel 
a = (1, 2, 3)
b = (40, 50, 60)
#baris ini akan menggabungkan nilai dari variabel a dan b menjadi c 
c = a + b
#baris ini akan menampilkan output dari kode di atas
print(c)

(1, 2, 3, 40, 50, 60)


In [17]:
#Latihan Tuples (8) dengan menggunakan count dan index

#inisialisasi variabel 
nilai_semester_1 = (78, 80, 90, 55, 78, 69, 100)

#baris ini akan menandai beberapa kali suatu elemen hadir di dalam tuples
print(nilai_semester_1.count(78))
#baris ini akan menemukan elemen dalam tuples 
print(nilai_semester_1.index(100))

2
6


***5.18 Dictionaries***

Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [18]:
#Latihan Dictionaries (1) dengan menggunakan 2 kata kunci yang sama

#inisialisasi variabel 
artikel = {
  "judul": "Aplikasi Komparasi Agoritma Peramalan",
  "judul": "Aplikasi Komparasi Agoritma Peramalan Dalam Kasus Penjualan Mobil"
}
#baris ini akan menampilkan judul dari variabel artikel
print(artikel.get("judul"))
#note : mengapa kata kunci pertama tidak muncul? 
#karena dictionary tidak bisa memiliki lebih dari satu key yang sama karena ia bersifat unique
#sehingga jika ada dua buah key yang sama, key yang didefinisikan terakhir akan menimpa nilai dari key yang didefinisikan lebih awal

In [19]:
#Latihan Dictionaries (2) dengan menggunakan fungsi len

#inisialisasi variabel
sekolah = {
  'nama': 'Sekolah Dasar Negeri Surabaya 1',
  'jenjang': 'Sekolah Dasar',
  'akreditasi': 'A'
}

#baris ini akan menampilkan jumlah elemen pada variabel sekolah
print(
  "Jumlah atribut variabel sekolah adalah:",
  len(sekolah)
)

Jumlah atribut variabel sekolah adalah: 3


In [20]:
#Latihan Doctionaries (3) dengan menggunakan operator keanggotaan

#inisialisasi variabel 
siswa = {
  'nama': 'Devano Danendra'
}
#baris ini akan menampilkan "apakah variabel siswa memiliki nama?"
print('Apakah variabel siswa memiliki nama?')
#baris ini akan menampilkan true or false dari sebuah pernyataan di atas
print('nama' in siswa)

#baris ini akan  menampilkan "apakah variabel siswa tidak memiliki usia?"
print('\nApakah variabel siswa TIDAK memiliki usia?')
#baris ini akan menampilkan true or false dari sebuah pernyataan diatas
print('usia' not in siswa)

Apakah variabel siswa memiliki nama?
True

Apakah variabel siswa TIDAK memiliki usia?
True


In [21]:
#Latihan Dictionaries (4) dengan menghapus item 2 cara 

#inisialisasi variabel 
mahasiswa = {
  'nama': 'Sitha Ariesta',
  'usia': 17,
  'asal': 'Bali'
}
#baris ini akan menghapus item dengan statement dibawah yaitu del<dict[key]>
del mahasiswa['nama']   #jika menggunakan statement ini, kita bisa mendaptkan nilai kembalian dari data yang telah di hapus 

#baris ini akan menghapus item dengan menggunakan fungsi dictionary.pop()
mahasiswa.pop('asal')   #jika menggunakan fungsi ini, kita bisa mendapatkan nilai kembalian dari data yang telah di hapus

'Bali'

In [28]:
#Latihan Dictionaries (5) dengan menambahkan item 

#inisialisasi variabel
mahasiswa = {
  'nama': 'Lendis Fabri',
  'asal': 'Indonesia',
}
#baris ini akan menghasilkan output kosong karena tidak ada hobi di dalam dict mahasiswa
print('Hobi:', mahasiswa.get('hobi'))
#baris ini akan menambahkan dict mahasiswa pada hobi yaitu memancing
mahasiswa['hobi'] = 'Memancing'
#baris ini akan menampilkan output dari kode diatas 
print(mahasiswa['asal'])

Hobi: None
Indonesia


In [29]:
#Latihan Dictionaries (6) dengan mengubah nilai item

#inisialisasi variabel 
mahasiswa = {
  'nama': 'Gita Herlina',
  'asal': 'Bali',
  'umur': 19
}
#baris ini akan mengubah data pada variabel mahasiswa
print('Nama awal:', mahasiswa.get('nama'))
mahasiswa['nama'] = 'Komang Widiarini'
print('Setelah diubah:', mahasiswa.get('nama'))

Nama awal: Gita Herlina
Setelah diubah: Komang Widiarini


In [30]:
#latihan Dictionaries (7) dengan menggunakan perulangan for

#inisialisasi variabel 
buku = {
  'judul': 'Hafalan Sholat Delisa',
  'penulis': 'Tere Liye'
}
#baris ini akan mengulang kata kunci yang terdapat pada variabel buku
for key in buku:
    #baris ini akan menampilkan output dari kode diatas
  print(key, '->', buku[key])

         #atau 
    
#baris ini akan mengulang nilai yang terdapat pada variabel buku
for nama_atribut, nilai in buku.items():
    #baris ini akan menampilkan output dari kode diatas
  print(nama_atribut, '->', nilai)

#output yang dihasilkan akan tetap sama

judul -> Hafalan Sholat Delisa
penulis -> Tere Liye
judul -> Hafalan Sholat Delisa
penulis -> Tere Liye


In [31]:
#Latihan Dictionaries (8) dengan membuat dan mengakses item pada variabel menggunakan dua cara 

#cara (1) membuat item
#inisialisasi variabel 
buku = {
  "judul": "Daun Yang Jatuh Tidak Pernah Membenci Angin",
  "penulis": "Tere Liye"
}
#cara (1) mengakses item dengan kurung siku []
print("Judul:", buku["judul"])

Judul: Daun Yang Jatuh Tidak Pernah Membenci Angin


In [32]:
#cara (2) membuat item 
#inisialisasi variabel 
buku = dict(
  judul="Daun Yang Jatuh Tidak Pernah Membenci Angin",
  penulis="Tere Liye"
)
#cara (2) mengakses item dengan menggunakan fungsi get()
print("Penulis:", buku.get("penulis"))

Penulis: Tere Liye


***5.19 Fungsi dalam Phyton***

Sampai sejauh ini tanpa disadari kita telah menerapkan beberapa jenis fungsi
pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi
dibentuk untuk menghidari pengulangan pembuatan program secara manual
dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang
kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat,
setiap fungsi tersebut dibutuhkan tinggal kita panggil.

In [36]:
#Latihan Fungsi dalam Phyton (1) dengan menggunakan fungsi def

#fungsi def adalah kumpulan perintah atau baris kode yang dikelompokkan menjadi satu kesatuan untuk kemudian bisa dipanggil atau digunakan berkali-kali
#sebuah fungsi def bisa menerima parameter, bisa mengembalikan suatu nilai, dan bisa dipanggil berkali-kali secara independen
#dengan fungsi ini kita bisa memecah program besar yang kita tulis, menjadi bagian-bagian kecil dengan tugasnya masing-masing

#input variabel first_name dan last_name
first_name = input("Nama depan anda adalah")
last_name = input("Nama belakang anda adalah")
#baris ini akan memblok variabel diatas menjadi sebuah variabel dengan nama full_name
def full_name(first_name,last_name):
    #baris ini akan menampilkan output dari kode diatas
    print(f"Nama lengkapnya adalah {nama_depam} {nama_belakang}")

Nama depan anda adalah Gita
Nama belakang anda adalah Herlina


In [48]:
#Latihan Fungsi dalam Phyton (2) dengan menggunakan lebih dari satu return 

#baris ini akan mendefinisikan persentase dengan total,jumlah
def persentase (total, jumlah):
    #jika total lebih besar atau sama dengan 0 dan total lebih kecil atau sama dengan jumlah
  if (total >= 0 and total <= jumlah):
    #maka akan mengembalikan nilai total dibagi jumlah dikali 100
    return total / jumlah * 100
  #maka akan mengembalikan nilai false
  return False
#baris ini akan menampilkan output dari presentase 
print(persentase(30, 60))
print(persentase(100, 60))

50.0
False


***5.19.1 Tugas Fungsi pada Phyton***

Ada dua jenis tugas fungsi pada Python yaitu:
1. Menjalankan perintah.
2. Menampilkan hasil perhitungan

In [57]:
#Latihan Tugas Fungsi pada phyton (1) yaitu menampilkan jumlah perhitungan

#baris ini akan mendefinisikan hitung_luas_segitiga dengan alas dan tinggi
def hitung_luas_segitiga():
  alas = 5
  tinggi = 7
    #baris ini akan menghitung luas dengan alas dikali tinggi dibagi 2
  luas = (alas * tinggi) / 2
#baris ini akan menampilkan output dari luas segitiga 
  print("Luas segitiga adalah: ",luas)
   
hitung_luas_segitiga()

Luas segitiga adalah:  17.5


In [58]:
#Latihan Tugas Fungsi pada Phyton (2) yaitu menjalankan perintah 

#inisialisasi variabel 
x=3
#baris ini akan mendefinisikan fungsi ubah dengan x = 5 
def ubah():
   x=5
#baris ini akan mengembalikan nilai x
   return x
#baris ini akan memanggil fungsi ubah
ubah()
#baris ini akan menampilkan nilai x
print(x)

3


In [59]:
#Latihan Tugas Fungsi pada Phyton (3) yaitu menampilkan hasil perhitungan 

#baris ini akan mendefinisikan fungsi fibonacci dengan n
def fibonacci (n):
    #jika n lebih kecil dari 1 maka akan mengembalikan nilai n
  if n < 1:
    return [n]
#baris ini akan menghitung list sebelumN, angka 1, dan angka 2 
  listSebelumN = fibonacci(n - 1)
  angka1 = listSebelumN[-2] if len(listSebelumN) > 2 else 0
  angka2 = listSebelumN[-1] if len(listSebelumN) > 2 else 1
#jika panjang list selum n angka1 dan angka2 lebih besar dari 2 maka akan mengembalikan nilai dari list sebelumN, angka 1, dan angka 2
  return listSebelumN + [angka1 + angka2]
#menginput panjang deret
panjang = int(input('Masukkan panjang deret:'))
#baris ini akan menampilkan output dari kode diatas, dan mengurangkan panjang dengan 1
print(fibonacci(panjang - 1))

Masukkan panjang deret: 25


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368]


In [61]:
#Latihan Tugas Fungsi pada Phyton (4) yaitu menjalankan perintah

#baris ini akan mendefinikan kalkulator total dengan price dan quatity
def calculate_total(price, quantity):
    """Fungsi untuk menghitung total harga.

    Args:
        price (int): Harga satuan barang.
        quantity (int): Jumlah barang yang dibeli.

    Returns:
        int: Total harga dari pembelian.

    """
    #baris ini akan menghitung total dengan price dikali quantity dan mengembalikan nilai total
    total = price * quantity
    return total
#inisialisasi variabel
harga_barang = 5000
jumlah_barang = 10
total_harga = calculate_total(harga_barang, jumlah_barang)
#baris ini akan menampilkan output dari kode di atas
print(f"Total harga: {total_harga}")

Total harga: 50000


In [62]:
#Latihan Tugas Fungsi Phyton (5) yaitu menampilkan hasil perhitungan 

#baris ini akan mendefinisikan hitung_luas_lingkaran dengan jari-jari, pi, 
def hitung_luas_lingkaran(jari_jari):
    pi = 3.14
    #baris ini akan menghitung luas lingkara dengan pi dikali jari-jari pangkat 2
    luas = pi * (jari_jari ** 2)
    #baris ini akan mengembalikan nilai luas
    return luas
#baris ini akan menginput jari-jari
jari_jari = float(input("Masukkan jari-jari lingkaran: "))
luas = hitung_luas_lingkaran(jari_jari)
#baris ini akan menampilkan output dari kode di atas
print(f"Luas lingkaran dengan jari-jari {jari_jari} adalah {luas}")

Masukkan jari-jari lingkaran:  14


Luas lingkaran dengan jari-jari 14.0 adalah 615.44


***5.20 Numpy***

Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan vektor dam matrik dalam berbagai dimensi. Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai
berikut:

In [74]:
import numpy as np

***5.20.1 Perintah Dasar pada Numpy***

In [76]:
#Latihan Perintah Dasar pada Phyton (1) dengan satu item

#inisialisasi variabel 
a = np.array([1, 2, 3, 4, 5, 6, 7])
#baris ini akan menampilkan output dari variabel a
print(a)

[1 2 3 4 5 6 7]


In [80]:
#Latihan Perintah Dasar pada Phyton (2) dengan menggunakan dua item 

#inisialisasi variabel 
x = np.array([[2, 4, 6, 8],[1, 3, 5, 9]])
#baris ini akan menampilkan output dari variabel x 
print(x)

[[2 4 6 8]
 [1 3 5 9]]


In [82]:
#Latihan Perintah Dasar pada Phyton (3) dengan menggunakan tiga item

#inisialisasi variabel 
c = np.array([[[11,12,13,14],[4,5,6,7]],
              [[3,6,9,4],[1,8,0,2]],
              [[0,8,5,2],[5,7,1,3]]])
#baris ini akan menampilkan output dari variabel c
print(c)            

[[[11 12 13 14]
  [ 4  5  6  7]]

 [[ 3  6  9  4]
  [ 1  8  0  2]]

 [[ 0  8  5  2]
  [ 5  7  1  3]]]


In [84]:
#Latihan Perintah Dasar pada Phyton (4) dengan menggunakan fungsi ndim

#inisialisasi variabel 
c = np.array([0,1,2,3])
#baris ini akan mengembalikan jumlah dimensi array
print(c.ndim)

1


In [85]:
#Latihan Perintah Dasar pada Phyton (5) dengan menggunakan fungsi shape

#insialisasi variabel 
z = np.array([11,13,15,17])
#baris ini akan menemukan bentuk array
print(z.shape)

(4,)


***5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy***

In [88]:
#Latihan Memanggil Anggota, Kolom dan Baris dengan Numpy (1)

#inisialisasi variabel
y = np.array([[0,3,7,5],[2,4,8,6],[1,14,21,36]])
#baris ini akan menampilkan anggota ke-2 pada baris ke-0 variabel y
print(y[0,2])
#baris ini akan menampilkan baris ke-1 pada variabel y
print(y[1,:])
#baris ini akan menampilkan kolom ke-4 pada variabel y
print(y[:,3])
#baris ini akan menampilkan anggota ke-1 dan ke-4 pada baris ke-0 variabel y
print(y[0,1:3])
#baris ini akan menampilkan anggota ke-0 dan ke-3 pada baris ke-0 variabel y
print(y[0,0:3:2])

7
[2 4 8 6]
[ 5  6 36]
[3 7]
[0 7]


In [90]:
#Latihan Memanggil Anggota, Kolom dan Baris (2) dengan mengubah anggota pada variabel 

#inisialisasi variabel
y = np.array([[0,3,7,5],[2,4,8,6],[1,14,21,36]])
y[0,2] = 55
#baris ini akan menampilkan isi dari variabel y setelah dirubah
print(y)

[[ 0  3 55  5]
 [ 2  4  8  6]
 [ 1 14 21 36]]


***5.20.3 Matriks pada Numpy***

In [92]:
#Latihan Matriks pada Numpy (1) dengan menggunakan fungsi zeros

#inisialisasi variabel
a = np.zeros((8,8))
#baris ini akan menampilkan output dari kode diatas
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [93]:
#Latihan Matriks pada Numpy (2) dengan menggunakan fungsi identity

#inisialisasi variabel 
b = np.identity(8)
#baris ini akan menampilkan output dari kode diatas
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [94]:
#latihan Matriks pada Numpy (3) 

#inisalisasi variabel 
c = 7*b
#baris ini akan menampilkan output dari kode diatas
print(c)

[[7. 0. 0. 0. 0. 0. 0. 0.]
 [0. 7. 0. 0. 0. 0. 0. 0.]
 [0. 0. 7. 0. 0. 0. 0. 0.]
 [0. 0. 0. 7. 0. 0. 0. 0.]
 [0. 0. 0. 0. 7. 0. 0. 0.]
 [0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 7. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7.]]


In [95]:
#Latihan Matriks pada Numpy (4)

#inisialisasi variabel 
d = np.ones((6,6))
e = np.identity(6)*6
f = d + e
#baris ini akan menampilkan output dari kode diatas
print(f)

[[7. 1. 1. 1. 1. 1.]
 [1. 7. 1. 1. 1. 1.]
 [1. 1. 7. 1. 1. 1.]
 [1. 1. 1. 7. 1. 1.]
 [1. 1. 1. 1. 7. 1.]
 [1. 1. 1. 1. 1. 7.]]


In [96]:
#Latihan Matriks pada Numpy (5)

#inisialisasi variabel 
c[1:-1,1:-1] = f
#baris ini akan menampilkan output dari kode diatas
print(c)

[[7. 0. 0. 0. 0. 0. 0. 0.]
 [0. 7. 1. 1. 1. 1. 1. 0.]
 [0. 1. 7. 1. 1. 1. 1. 0.]
 [0. 1. 1. 7. 1. 1. 1. 0.]
 [0. 1. 1. 1. 7. 1. 1. 0.]
 [0. 1. 1. 1. 1. 7. 1. 0.]
 [0. 1. 1. 1. 1. 1. 7. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7.]]


***5.20.4 Copy pada Numpy***

In [99]:
#Latihan Copy pada Numpy (1)

#inisialisasi variabel 
a = np.array([2,4,6,8,10])
#baris ini akan menampilkan elemen dari variabel a
print(a)
#baris ini akan menginisialisasi b sama dengan a
b = a
#baris ini akan menampilkan elemen dari variabel b
print(b)

[ 2  4  6  8 10]
[ 2  4  6  8 10]


In [101]:
#Latihan Copy pada Numpy (2)

#inisialisasi variabel 
c = np.array([1,3,5,7,9])
#baris ini akan menampilkan elemen dari variabel c
print(c)
#baris ini akan mengcopy variabel c agar menghindari variabel awal yang tidak dikehendaki maka menggunakan perintah copy
d = c.copy()
#baris ini akan menampilkan elemen dari variabel d
print(d)

[1 3 5 7 9]
[1 3 5 7 9]


***5.20.5 Operasi Matematika pada Numpy***

In [103]:
#Latihan Operasi Matematika pada Numpy (1) dengan menggunakan penjumlahan,pengurangan,perkalian,pembagian,pemangkatan pada bilangan bulat

#inisialisasi variabel
x = np.array([4,3,2,1])
#baris ini akan menjumlahkan variabel x dengan 2
print(x + 2)
#baris ini akan mengurangi variabel x dengan 1
print(x - 1)
#baris ini akan mengalikan variabel x dengan 3
print(x * 3)
#baris ini akan membagi variabel x dengan 2 
print(x/2)
#baris ini akan mempangkatkan variabel x 
print(x**3)

[6 5 4 3]
[3 2 1 0]
[12  9  6  3]
[2.  1.5 1.  0.5]
[64 27  8  1]


In [104]:
#Latihan Operasi pada Numpy (2) dengan penjumlahan,pengurangan,pembagian,perkalian, dan pemangkatan dengan variabel yang berbeda

#inisialisasi variabel
x = np.array([4,3,2,1])
y = np.array([9,8,7,6])
#baris ini akan menjumlahkan variabel x dengan y
print(x + y)
#baris ini akan mengurangi variabel x dengan y
print(x - y)
#baris ini akan mengalikan variabel x dengan y
print(x * y)
#baris ini akan membagi variabel x dengan y
print(x/y)
#baris ini akan mempangkatkan variabel y dengan x 
print(y**x)

[13 11  9  7]
[-5 -5 -5 -5]
[36 24 14  6]
[0.44444444 0.375      0.28571429 0.16666667]
[6561  512   49    6]


In [106]:
#Latihan Operasi pada Numpy (3) dengan cos,tan,sin dan sqrt

#inisialisasi variabel 
a = np.cos([4,2,5])
b = np.sin([1,3,2])
c = np.tan([9,1,0])
d = np.sqrt([7,8,1])
#baris ini akan menampilkan ouput dari kode diatas
print(a)
print(b)
print(c)
print(d)

[-0.65364362 -0.41614684  0.28366219]
[0.84147098 0.14112001 0.90929743]
[-0.45231566  1.55740772  0.        ]
[2.64575131 2.82842712 1.        ]


***5.20.6 Perkalian Matrik pada Numpy***

In [107]:
#Latihan Perkalian Matrik pada Numpy (1) dengan metode biasa 

#inisialisasi variabel 
a = np.array([7,3,0,1])
b = np.array([2,4,8,6])
c = a*b
#baris ini akan menampilkan output dari kode diatas
print(c)

[14 12  0  6]


In [108]:
#Latihan Perkalian Matrik pada Numpy (2) dengan menggunakan perintah matmul

#inisialisasi variabel 
x = np.array([2,5,9,0])
y = np.array([1,4,7,3])
e = np.matmul(x,y)
#baris ini akan menampilkan output dari kode diatas 
print(e)

85


***5.20.7 Min, Max, dan Sum pada Numpy***

In [109]:
#Latihan Min, Max, dan Sum pada Numpy (1) 

#inisialisasi variabel
c = np.array([[[11,12,13,14],[4,5,6,7]],
              [[3,6,9,4],[1,8,0,2]],
              [[0,8,5,2],[5,7,1,3]]])
#baris ini akan menampilkan elemen dari variabel c
print(c)

#baris ini akan menginisialisasi variabel 
b = np.min(c)
#baris ini akan menampilkan output dari kode diatas
print(b)
#baris ini akan menginisialisasi variabel 
d = np.max(b)
#baris ini akan menampilkan output dari kode diatas
print(d)
#baris ini akan menginisialisasi variabel 
e = np.sum(c)
#baris ini akan menampilkan output dari kode diatas 
print(e)

[[[11 12 13 14]
  [ 4  5  6  7]]

 [[ 3  6  9  4]
  [ 1  8  0  2]]

 [[ 0  8  5  2]
  [ 5  7  1  3]]]
0
0
136


In [110]:
#Latihan Min, Max, dan Sum pada Numpy (2) 

#inisialisasi variabel
c = np.array([[[11,12,13,14],[4,5,6,7]],
              [[3,6,9,4],[1,8,0,2]],
              [[0,8,5,2],[5,7,1,3]]])
f = np.max(c,axis=0)
g = np.sum(f,axis=1)
h = np.min(c,axis=0)
#baris ini akan menampilkan output dari kode diatas
print(f)
print(g)
print(h)

[[11 12 13 14]
 [ 5  8  6  7]]
[50 26]
[[0 6 5 2]
 [1 5 0 2]]
